### ISSUE TITLE
[BUG] Initial comment missing

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#103]
### Issue Summary

<img width="994" alt="image" src="https://github.com/user-attachments/assets/28d77a70-de57-4f73-b447-63d6c1d0bfb9">

Usually, the bot issues a comment "Excited to have you ship this!"

Sometimes it doesn't comment

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

comment

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Dhruwang** [comment]
Should be fixed with this 
https://github.com/formbricks/oss.gg/pull/100

**Comment by jobenjada** [comment]
/oss.gg 50
