### ISSUE TITLE
[BUG]: Signed in user can still see the Sign Up button

### ISSUE THREAD

**Issue by harshsbhat** [formbricks/oss.gg#126]
### Issue Summary

When I signup and go to github.com/myusername it shows me the option to signup 

![image](https://github.com/user-attachments/assets/b229e21c-60a5-46e6-a5fb-6a8a0788f1c0)

### Steps to Reproduce

1. Go to oss.gg
2. Sign up
3. See you need to signup on oss.gg/username

### Expected behavior

The signup button their shouldn't exist as I am already signed in

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Tanuj1718** [comment]
@mattinannt @jobenjada  I would like to work on it, can you please assign it to me?

**Comment by harshsbhat** [comment]
it's resolved
