### ISSUE TITLE
[BUG] Wrong link on "iPhone 16 with 512GB Link" under prizes

### ISSUE THREAD

**Issue by piyushgarg-dev** [formbricks/oss.gg#127]
### Issue Summary

The link for 'iPhone 16 with 512GB Link' points to 'iPad' instead of the iPhone 16 landing page on the home page.

### Steps to Reproduce

1. Visit https://oss.gg/
2. Explad Prizes section
3. Click [iPhone 16 with 512GB](https://www.apple.com/ipad-pro/)
4. You will be redirected to the iPad landing page.

### Expected behavior

The link must point to https://www.apple.com/iphone-16/

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by Tanuj1718** [comment]
@jobenjada @mattinannt Can you please review the above #130 PR?
