### ISSUE TITLE
[FEATURE] Github repository link.

### ISSUE THREAD

**Issue by MeerUzairWasHere** [formbricks/oss.gg#134]
### Is your feature request related to a problem? Please describe.

It would be great if we put GitHub repository links also here
![image](https://github.com/user-attachments/assets/07f7526d-704f-4e8a-a4a8-4eb2c9acbe6a)

### Describe the solution you'd like

I want to click on a logo or a link which will take me to that GitHub repository like dubdotco, formbricks etc

### Describe alternatives you've considered

link on logo or a link button

### Additional context

I would love to work on it, if you'll assign this to me. Thanks ;)

**Comment by MeerUzairWasHere** [comment]
> /assign

thought it'll work here too, lol

**Comment by a19hu** [comment]
@MeerUzairWasHere are you working on this issue ?

**Comment by thekbbohara** [comment]
I have already created this issue https://github.com/formbricks/oss.gg/issues/133

**Comment by MeerUzairWasHere** [comment]
-_-

**Comment by thekbbohara** [comment]
> -_-

hey do you wanna work on this issue #136

**Comment by MeerUzairWasHere** [comment]
> > -_-
> 
> hey do you wanna work on this issue #136

Nah. Thanks.
