### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by nathanclevenger** [formbricks/oss.gg#15]
### Issue Summary

After signing in via Github, an error occurred and the login failed

Invalid `prisma.account.create()` invocation:

### Steps to Reproduce

1. Logged In via Github
2. Error in Auth.js on Callback

{
  data: {
    provider: "github",
    type: "oauth",
    providerAccountId: "xxxxxx",
    access_token: "ghu_xxxxx",
    expires_at: 1709073049,
    refresh_token: "ghr_xxxxxx",
    refresh_token_expires_in: 15724800,
    ~~~~~~~~~~~~~~~~~~~~~~~~
    token_type: "bearer",
    scope: "",
    userId: "xxxx",
?   id?: String,
?   id_token?: String | Null,
?   session_state?: String | Null,
?   createdAt?: DateTime,
?   updatedAt?: DateTime
  }
}

Unknown argument `refresh_token_expires_in`. Available options are marked with ?.

### Expected behavior

Expected login redirect

### Other information

Interestingly, after trying to log in a second time, I was redirected to the dashboard successfully ...

### Screenshots

_No response_

### Desktop (please complete the following information)

```markdown
- Browser: Safari 17.2.1
```

**Comment by ShubhamPalriwala** [comment]
Hey @nathanclevenger thanks for flagging this! We'll take a look right away 💪🏼 And keep you posted

**Comment by ShubhamPalriwala** [comment]
Hey, we have fixed it! It was an app misconfiguration issue as we had enabled the Optional Refresh Token functionality!

Thanks again 🚀
