### ISSUE TITLE
[FEATURE] Enable Account Deletion

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#32]
### Is your feature request related to a problem? Please describe.

To make sure players have full control over their data, we let them delete their oss.gg account.

### Describe the solution you'd like

1. Create a settings page with a card "Account" and add a "Delete Account" button.
2. Open a confirm modal before deleting the account

Here is a low fidelity mock up (the colors and text sizes in the app are not yet aligned with Figma):

<img width="749" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/e8b04dcc-39e1-4752-896c-7ec128397eb8">

Thanks!

**Comment by nik132-eng** [comment]
/assign 

i like to work on this issue
