### ISSUE TITLE
[FEATURE] Build a reusable Tabs component and add tabs to the project layout

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#33]
### Is your feature request related to a problem? Please describe.

Currently, we're missing tabs

### Describe the solution you'd like

1. Use shadcn tabs to build a reusable tab component in the `packages/ui` folder:

https://ui.shadcn.com/docs/components/tabs

2. Then, introduce the "Project Details", "Leaderboard", and "Open Issues" tabs to the Project Details page:

<img width="736" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/b4eb50d1-d384-4fda-ac8f-d5cb6e17aaeb">

<img width="743" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/d1c5ca00-498a-4b40-9abf-f89bca755ed5">

<img width="735" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/d5b0ac9a-3aad-44de-a667-34892c73d024">

Here is the Figma file for more context:

https://oss.gg/figma

If anything is unclear, ask @jobenjada in the oss.gg Discord: https://oss.gg/discord

Thanks!!

**Comment by raysubham** [comment]
@jobenjada Would love to pick this ?

**Comment by jobenjada** [comment]
its all your, lets do this! 💪 :)

**Comment by raysubham** [comment]
> hey @raysubham thanks for the PR 🙌
> 
> I've merged it so that Chigala can use the tabs for the repo settings. However, please open a new PR to display all open issues per repository in the "Open Issue" tab.
> 
> Thanks! :)

On it.
