### ISSUE TITLE
[FEATURE] Build Leaderboard

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#34]
### Is your feature request related to a problem? Please describe.

Currently, we don't have a leaderboard

### Describe the solution you'd like

In this issue #33 we're building tabs. In one of the tabs, we want to display a leaderboard - ship it :)

Please have a look at the Figma file for more context: oss.gg/figma

<img width="845" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/ebc59db8-71ca-46c4-9269-259cceae39a1">

1. Currently the mock up is missing the avatar, pls include it :)
2. The name links in a new tab to their github profile
3. The leaderboard should be sorted by level. Find a nice way to show that in the UI. We can always tweak it in the review.

### Technical Considerations

Please build the component to display each user so that it can be augmented for this functionality on the repository settings page down the line:

<img width="844" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/b9d785ff-d1f1-4d9c-8a6e-b51101483799">

**Comment by raysubham** [comment]
@jobenjada Can also pick this along with the Tabs PR ?

**Comment by jobenjada** [comment]
lets do a feedback cycle with the tabs first and then get back to this one :)

**Comment by manish-singh-bisht** [comment]
i want to work on this. @jobenjada

**Comment by jobenjada** [comment]
hey @manish-singh-bisht have assigned you, feel free to get started. @raysubham let's give everyone a chance to contribute :) There is more than enough to work on 🖖

**Comment by manish-singh-bisht** [comment]
@jobenjada it is just the ui right? i have used dummy data to show the functionality.

 do i have to build the backend functionality for this as well?

**Comment by jobenjada** [comment]
@manish-singh-bisht I've added points to this issue now :)
