### ISSUE TITLE
[PM TASK] Research bounty system and write it up

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#36]
### Is your feature request related to a problem? Please describe.

We currently only have a vague idea on how to implement the bounty system. We need more research!

### Describe the solution you'd like

Please have a look at these resources:

https://github.com/muddleco/muddle

https://osshack.com/

@baileypumfleet gave his go that we can use the bounty platform he built for the OSSHack to power bounties on oss.gg 🙏🙏🙏

### Tasks

1. Research how bounties were implemented technically
2. Analyse how the bounties are used within OSSHack - e.g. all bounties above $400 needed manual approval
3. Write up a detailed concept on how oss.gg should handle bounties including:
- technical considerations
- cost attached to handing out bounties and how they could be covered best
- wireframes
- other UX considerations

also, see this ticket #29

**Comment by BlessingOjediran** [comment]
[Link to Bounties Concept here](https://blessingojediran.notion.site/Bounty-System-A-Unified-Concept-98036ce70e954d78a76f2afb76fec88e?pvs=4) @jobenjada

**Comment by AliYar-Khan** [comment]
use Algora.io Instead !!!
