### ISSUE TITLE
[COMMUNITY] Setup Discord channel (Roles, etc.)

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#44]
### Is your feature request related to a problem? Please describe.

its a blank channel so far :)

### Describe the solution you'd like

bring it to live :) would love to see a role for founding team members 🤓

**Comment by nik132-eng** [comment]
can you elaborate more? Do you want to create channels or role name suggestions?

**Comment by Blackmercii2** [comment]
I'm picking this up.

**Comment by jobenjada** [comment]
@Blackmercii2 pls make a PR to add your contribution to the list so this issue gets closed and you can get points assigned :)

**Comment by Blackmercii2** [comment]
@jobenjada i’m on it
