### ISSUE TITLE
[BUG] Fix hard coded page title

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#55]
### Issue Summary

<img width="711" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/79d81e06-a02a-41a7-8069-1123c3807353">

currently, the page title of the enroll/repositoryId is always "Formbricks | oss.gg"

### Steps to Reproduce

1. go to a repo detail page

### Expected behavior

remove the hard-coded page title and replace "Formbricks" with the actual repository name.

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jobenjada** [comment]
@Barry-dE any updates? :)

**Comment by Barry-dE** [comment]
I've been sick. Just recovered. I'll look into it.

**Comment by Barry-dE** [comment]
I ran into an error trying to reproduce the issue. It's running in development, but when I try to access it, I get an error. Maybe it's from my end, I'll try to figure out what's wrong.

**Comment by nik132-eng** [comment]
> I ran into an error trying to reproduce the issue. It's running in development, but when I try to access it, I get an error. Maybe it's from my end, I'll try to figure out what's wrong.

you can share your error on discord so if anyone have time they can help you out
