### ISSUE TITLE
[FEATURE] Set readme as Project Details

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#56]
### Is your feature request related to a problem? Please describe.

Currently, the project details card is empty:

<img width="749" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/8059e444-fb1d-4d28-a00c-10d3cab1f6a9">

### Describe the solution you'd like

**This isn't an easy task, so please only assign yourself if you bring enough experience to complete it 🤓**

Our goal is the following in a nutshell:

1. Pull readme from repo on creation
2. Set readme content as projectDetails
3. Display it parsing the MDX correctly

More context:

### Pull readme from repo on creation
When a maintainer connects oss.gg with their repo, we create a repository and an installation in the oss.gg database. Have a look at this file as a starting point:

https://github.com/formbricks/oss.gg/blob/main/lib/github/hooks/installation.ts

We likely need a new service which pulls the readme from a repo via the GitHub API, but it's your task to find that out and propose a solution 🤓 

### Set readme content as projectDetails
We already have `projectDescription String?` field in the Prisma schema. Store it there.

### Display it parsing the MDX correctly
Pick a widely used and performant package to then parse the string into rich text. Display it here:

<img width="1200" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/f7d75b15-1b4c-4260-a245-116650f49607">

**Comment by manish-singh-bisht** [comment]
Will give it a shot.

/assign

**Comment by mdhruvil** [comment]
@jobenjada Can we fetch the repo readme [here](https://github.com/formbricks/oss.gg/blob/154a4521daa62613bbb79bc53db9f74844a404c3/lib/github/services/user.ts#L109C22-L109C32) and upsert here
