### ISSUE TITLE
[BUG] Fix why wrong issues are displayed

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#57]
### Issue Summary

We're not getting the most uptodate data from GitHub (likely a caching issue).

This is the current status of issues:

<img width="775" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/5ad0aaca-eabe-4925-85d0-60a88bb92dec">

And this is what gets displayed (despite removeing local storage, etc):

<img width="1193" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/d6943a81-1717-45cd-b30d-432ee49c4abc">

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

### Expected behavior

At least of hard refresh the newest issues should be pulled.

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

**Comment by jayprakash98** [comment]
I think this issus  is solved , when I try to reproduce its showing currently open issues

**Comment by nik132-eng** [comment]
If you reload the page it is properly working for me in a dev environment

**Comment by priyankarpal** [comment]
it's working for me

![Screenshot_2024-04-13_15_48_35](https://github.com/formbricks/oss.gg/assets/88102392/83f3b31d-a17d-4ea9-98f2-e57a21e761b4)

**Comment by raysubham** [comment]
@jobenjada This bug is likely due to the `24hrs` cache time which is currently set. We may to decrease this to avoid stale data.
