### ISSUE TITLE
[FEATURE] Add repository name to meta data on open issue page

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#58]
### Is your feature request related to a problem? Please describe.

Currently, we don't see which repo an issue belongs to:

<img width="231" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/54e98a2c-88f2-4db2-a8be-9101ebed62da">

### Describe the solution you'd like

add the repo name to the meta data line 

"opened by jobenjada in formbricks" like so

<img width="403" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/58e3c4ea-ab2d-4155-b632-43e5205df590">

**Comment by raysubham** [comment]
Unasssigning myself from this issue so that I can pick up another issue: https://github.com/formbricks/oss.gg/issues/56
