### ISSUE TITLE
[FEATURE] Replace Player List Item with Leaderboard List Item

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#77]
### Is your feature request related to a problem? Please describe.

Currently, the play list looks like this:

<img width="767" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/c71e1357-7072-44c4-a5e6-27ead0864500">

### Describe the solution you'd like

But we already have a better component for that in the Leaderboard:

<img width="523" alt="image" src="https://github.com/formbricks/oss.gg/assets/72809645/ab693f2d-b95e-477a-a994-b83119c7584a">

Reuse this component to display players :)

**Comment by manish-singh-bisht** [comment]
i took permission from @tobihans before making this pr.

**Comment by tobihans** [comment]
> i took permission from @tobihans before making this pr.
> 

I confirm. Thanks. Sorry I can't make it due to my busy schedule.
