### ISSUE TITLE
[FEATURE] If a PR has oss.gg and points assigned as labels, it should auto award on merge

### ISSUE THREAD

**Issue by jobenjada** [formbricks/oss.gg#86]
### Is your feature request related to a problem? Please describe.

currently, we have to award manually (and sometimes we forget 😇 )

### Describe the solution you'd like

if a PR has oss.gg label and points label lets auto award points and post a comment on the PR so everyone is informed :)

**Comment by jobenjada** [comment]
go for it! :)

**Comment by ebe25** [comment]
@RajuGangitla hey man are you still working on this?

**Comment by RajuGangitla** [comment]
yeah i am working on it @ebe25
