### ISSUE TITLE
[BUG] Fetch user info and contributions properly

### ISSUE THREAD

**Issue by RA9** [formbricks/oss.gg#94]
### Issue Summary

Our current system only recognizes contributions from users with accounts on this platform. This means valuable contributions from unregistered users, like those who contribute to open-source projects on platforms like `freeCodeCamp`, might go unnoticed.

### Steps to Reproduce

1. https://oss.gg/jobenjada
2. https://oss.gg/benjaminangafua

### Expected behavior

For repositories using oss.gg, if contributor objects lack a corresponding user record in our system, we will attempt to verify their contributions through the repository's data. If verification fails, the user will be prompted to create an account for proper attribution.

### Screenshots

![image](https://github.com/formbricks/oss.gg/assets/20514920/e4aec25c-6931-4567-9062-1bba9c61f773)
![image](https://github.com/formbricks/oss.gg/assets/20514920/06b450a2-3083-406b-8453-588d6df3245f)

### Desktop (please complete the following information)

```markdown
- OS:
Edge
- Node:
v22.2.0
- npm:
10.7.0
```

**Comment by jobenjada** [comment]
should be solved :)
