### ISSUE TITLE
[BUG] Profile Page Text is hard to see 

### ISSUE THREAD

**Issue by sameer-dudeja** [formbricks/oss.gg#96]
### Issue Summary

![image](https://github.com/user-attachments/assets/d37585ee-3f18-4ae1-ae33-444b92f28dcc)
On the profile page, the card which is conveying that I have not made a contribution should be visible properly.  

### Steps to Reproduce

1. Signed up using Github
2. Enrolled in a repo 
3. Opened profile page
![image](https://github.com/user-attachments/assets/361a26d9-624f-41a8-b5de-cb8f9a04511e)

### Expected behavior

![image](https://github.com/user-attachments/assets/604f8a42-71f5-41fe-95ff-6caaef4064d0)
Should be something like this

### Desktop (please complete the following information)

```markdown
- OS: Windows
- Browser: Chrome
```

**Comment by sameer-dudeja** [comment]
Also found places where button text was not visible, is it by design?  
![image](https://github.com/user-attachments/assets/4ee8cbb8-2c72-47b5-a249-a02762d5a114)

If its not by design then, I can include the fix in #97

**Comment by jobenjada** [comment]
we're doing a complete revamp of the UI so im closing this :)
